/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cem.view;

//import cem.view.dialogsMenu2.WatchStatsDialog1;
//import cem.view.dialogsMenu2.EditParticipantDialog1;
//import cem.view.dialogsMenu2.CreateMarxaDialog1;
//import cem.view.dialogsMenu2.ShowMarxes1;
import cem.view.dialogsMenu2.ChoseParticipant;
import cem.view.dialogsMenu2.CreateMarxaDialog1;
import cem.view.dialogsMenu2.RegisterParticipantDialog1;
import cem.view.dialogsMenu2.ShowMarxes1;
import cem.view.dialogsMenu2.EstadistiquesMarxaDialog1;
import cem.view.dialogsMenu2.subMenuMarxes.ChoseParticipants;

/**
 *
 * @author HexaJIA
 */
public class MenuJFrame extends javax.swing.JFrame {

    //atributos
    private ShowMarxes1 showMarxes;
    private CreateMarxaDialog1 createMarxaDialog;
    private RegisterParticipantDialog1 registerParticipantDialog;
    private EstadistiquesMarxaDialog1 estadistiquesMarxaDialog;
    private ChoseParticipant choseParticipantDialog;

    /**
     * Creates new form NewJFrame
     */
    public MenuJFrame() {
        initComponents();
        setTitle("Menu principal");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanelMenu = new javax.swing.JPanel();
        exitPanel = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        buttonsPanel = new javax.swing.JPanel();
        createMarxaButton = new javax.swing.JButton();
        modifyRunnerButton = new javax.swing.JButton();
        marxesButton = new javax.swing.JButton();
        createRunnerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ParticipantsMarxajButton = new javax.swing.JButton();
        eliminarParticiant = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        exitPanel.setBackground(new java.awt.Color(0, 153, 204));
        exitPanel.setToolTipText("");

        exitButton.setText("SORTIR");
        exitButton.setAlignmentY(0.0F);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("UNIÓ MUNTANYENCA ERAMPRUNYÀ");

        javax.swing.GroupLayout exitPanelLayout = new javax.swing.GroupLayout(exitPanel);
        exitPanel.setLayout(exitPanelLayout);
        exitPanelLayout.setHorizontalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(exitButton)
                .addGap(49, 49, 49))
        );
        exitPanelLayout.setVerticalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        buttonsPanel.setBackground(new java.awt.Color(204, 255, 255));

        createMarxaButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createMarxaButton.setText("Crear marxa");
        createMarxaButton.setAlignmentY(0.0F);
        createMarxaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createMarxaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMarxaButtonActionPerformed(evt);
            }
        });

        modifyRunnerButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        modifyRunnerButton.setText("Modificar participant");
        modifyRunnerButton.setAlignmentY(0.0F);
        modifyRunnerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modifyRunnerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyRunnerButtonActionPerformed(evt);
            }
        });

        marxesButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        marxesButton.setText("Marxes");
        marxesButton.setAlignmentY(0.0F);
        marxesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        marxesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marxesButtonActionPerformed(evt);
            }
        });

        createRunnerButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createRunnerButton.setText("Alta participant");
        createRunnerButton.setAlignmentY(0.0F);
        createRunnerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createRunnerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRunnerButtonActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ume_escut_90.gif"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setMaximumSize(new java.awt.Dimension(78, 91));

        ParticipantsMarxajButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ParticipantsMarxajButton.setText("Estadístiques de les marxes");
        ParticipantsMarxajButton.setAlignmentY(0.0F);
        ParticipantsMarxajButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ParticipantsMarxajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParticipantsMarxajButtonActionPerformed(evt);
            }
        });

        eliminarParticiant.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eliminarParticiant.setText("Eliminar Participant");
        eliminarParticiant.setAlignmentY(0.0F);
        eliminarParticiant.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminarParticiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarParticiantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsPanelLayout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ParticipantsMarxajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(buttonsPanelLayout.createSequentialGroup()
                        .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createRunnerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modifyRunnerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createMarxaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(marxesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminarParticiant, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonsPanelLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonsPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(marxesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(createMarxaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(createRunnerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(modifyRunnerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(eliminarParticiant, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(ParticipantsMarxajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundPanelMenuLayout = new javax.swing.GroupLayout(backgroundPanelMenu);
        backgroundPanelMenu.setLayout(backgroundPanelMenuLayout);
        backgroundPanelMenuLayout.setHorizontalGroup(
            backgroundPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundPanelMenuLayout.createSequentialGroup()
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(exitPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundPanelMenuLayout.setVerticalGroup(
            backgroundPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelMenuLayout.createSequentialGroup()
                .addComponent(exitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //boton que sirve para saler del jframe
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    //abre el jdialog RegisterPArticipant
    private void createRunnerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRunnerButtonActionPerformed
        // TODO add your handling code here:
        registerParticipantDialog = new RegisterParticipantDialog1(this, true, null);
        setVisible(false);
        registerParticipantDialog.setVisible(true);
        setVisible(true);
    }//GEN-LAST:event_createRunnerButtonActionPerformed

    //abre el jdialog CreateMarxw
    private void createMarxaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMarxaButtonActionPerformed
        createMarxaDialog = new CreateMarxaDialog1(this, true);
        setVisible(false);
        createMarxaDialog.setVisible(true);
        setVisible(true);    }//GEN-LAST:event_createMarxaButtonActionPerformed

    //abre el jdialog ShowMarxes
    private void marxesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marxesButtonActionPerformed
        // TODO add your handling code here:
        showMarxes = new ShowMarxes1(this, true);
        setVisible(false);
        showMarxes.setVisible(true);
        setVisible(true);
    }//GEN-LAST:event_marxesButtonActionPerformed

    //abre el jdialog ChoseParticipant
    private void modifyRunnerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyRunnerButtonActionPerformed
        choseParticipantDialog = new ChoseParticipant(this, true, false);
        setVisible(false);
        choseParticipantDialog.setLocationRelativeTo(this);
        choseParticipantDialog.setVisible(true);
        setVisible(true);
    }//GEN-LAST:event_modifyRunnerButtonActionPerformed

    //abre el jdialog EstadistiquesMarxa
    private void ParticipantsMarxajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParticipantsMarxajButtonActionPerformed
        // TODO add your handling code here:
        estadistiquesMarxaDialog = new EstadistiquesMarxaDialog1(this, true);
        setVisible(false);
        estadistiquesMarxaDialog.setLocationRelativeTo(this);
        estadistiquesMarxaDialog.setVisible(true);
        setVisible(true);
    }//GEN-LAST:event_ParticipantsMarxajButtonActionPerformed

    private void eliminarParticiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarParticiantActionPerformed
        ChoseParticipant window = new ChoseParticipant(this,true,true);
        setVisible(false);
        window.setLocationRelativeTo(this);
        window.setVisible(true);
    }//GEN-LAST:event_eliminarParticiantActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ParticipantsMarxajButton;
    private javax.swing.JPanel backgroundPanelMenu;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton createMarxaButton;
    private javax.swing.JButton createRunnerButton;
    private javax.swing.JButton eliminarParticiant;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel exitPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton marxesButton;
    private javax.swing.JButton modifyRunnerButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
