/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package cem.view.dialogsMenu2;

import cem.controller.Controller;
import cem.model.TO.ParticipantEditionTO;
import cem.model.TO.StatsMarxesTO;
import cem.view.dialogsMenu2.subMenuMarxes.MarxesDialog1;
import cem.view.dialogsMenu2.subMenuMarxes.RankingInscripcionsMarxa;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class EstadistiquesMarxaDialog1 extends javax.swing.JDialog {
    //atributos
    private Controller controller;
    private java.awt.Frame parent;

    /**
     * Creates new form EstadistiquesMarxaDialog1
     */
    //constructor
    public EstadistiquesMarxaDialog1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        setTitle("Estadistiques de les marxes");
        setModal(true);
        pack();
        setResizable(false);
        initComponents();
        setLocationRelativeTo(null);
        controller = Controller.getInstance();
        listStatsMarxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exitjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        statsjTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ESTADÍSTIQUES DE LES MARXES");

        exitjButton.setText("sortir");
        exitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(390, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(390, 390, 390))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(exitjButton)
                        .addGap(10, 10, 10))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(exitjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        statsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Edició", "Inscrits", "En cursa", "Arribats", "Absents", "Abandonat", "Temps més ràpid", "Temps més lent"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        statsjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statsjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(statsjTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //crea una rankingInscripcionMarxa cuando das clic en la marxa
    private void statsjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsjTableMouseClicked
        // TODO add your handling code here:
        JTable source = (JTable)evt.getSource();
        int row = source.rowAtPoint( evt.getPoint() );
        int column = source.columnAtPoint( evt.getPoint() );
        String s=source.getModel().getValueAt(row, 0)+"";
        this.setVisible(false);
        RankingInscripcionsMarxa rankingInscripcionsMarxa;
        try {
            rankingInscripcionsMarxa = new RankingInscripcionsMarxa(parent,true,s);
            rankingInscripcionsMarxa.setLocationRelativeTo(this);
            rankingInscripcionsMarxa.setVisible(true);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        this.setVisible(true);
    }//GEN-LAST:event_statsjTableMouseClicked

    //boton salir
    private void exitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitjButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitjButtonActionPerformed

    //muestra la tabla con los nombres de los titulos y se va modificando cuando se añade alguna Marxa
    private void listStatsMarxes() {
        try {
            ArrayList<StatsMarxesTO> stats = controller.getStatsMarxes();
            DefaultTableModel dtm = new DefaultTableModel(new String[]{"Edició", "Inscrits", "En cursa", "Arribat", "Absent", "Abandonat", "Temps més ràpid", "Temps més lent"}, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // ninguna celda editable
                }
            };
            for (StatsMarxesTO p : stats) {
                String rapid = p.getTempsMesRapid() != null ? p.getTempsMesRapid() : "--:--:--";
                String lent = p.getTempsMesLent() != null ? p.getTempsMesLent() : "--:--:--";
                dtm.addRow(new String[]{p.getEdicio(), p.getInscrits(), p.getEnCursa(), p.getArribats(), p.getAbsents(), p.getAbandonat(), rapid, lent});
            }
            statsjTable.setModel(dtm);
        } catch (SQLException ex) {
            System.out.println("ERROR SQL (no debería darse): " + ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable statsjTable;
    // End of variables declaration//GEN-END:variables
}
