/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package cem.view.dialogsMenu2;

/**
 *
 * @author Usuario
 */
public class RegisterParticipantDialog1 extends javax.swing.JDialog {

    /**
     * Creates new form RegisterParticipantDialog
     */
    public RegisterParticipantDialog1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Registrar esportista");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlesjPanel = new javax.swing.JPanel();
        DNIjLabel = new javax.swing.JLabel();
        namejLabel = new javax.swing.JLabel();
        cognomsjLabel = new javax.swing.JLabel();
        birthDatejLabel = new javax.swing.JLabel();
        sexejLabel = new javax.swing.JLabel();
        townjLabel = new javax.swing.JLabel();
        telfjLabel = new javax.swing.JLabel();
        mailjLabel = new javax.swing.JLabel();
        fedejCheckBox = new javax.swing.JCheckBox();
        valuesjPanel = new javax.swing.JPanel();
        DNIjTextField = new javax.swing.JTextField();
        namejTextField = new javax.swing.JTextField();
        cognomsjTextField = new javax.swing.JTextField();
        townjTextField = new javax.swing.JTextField();
        telfjTextField = new javax.swing.JTextField();
        mailjTextField = new javax.swing.JTextField();
        fedejTextField = new javax.swing.JTextField();
        birthDatejSpinner = new javax.swing.JSpinner();
        sexejComboBox = new javax.swing.JComboBox<>();
        acceptjButton = new javax.swing.JButton();
        canceljButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titlesjPanel.setBackground(new java.awt.Color(0, 153, 204));

        DNIjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DNIjLabel.setForeground(new java.awt.Color(255, 255, 255));
        DNIjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DNIjLabel.setText("DNI/NIF");

        namejLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namejLabel.setForeground(new java.awt.Color(255, 255, 255));
        namejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namejLabel.setText("Nom");

        cognomsjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cognomsjLabel.setForeground(new java.awt.Color(255, 255, 255));
        cognomsjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cognomsjLabel.setText("Cognoms");

        birthDatejLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        birthDatejLabel.setForeground(new java.awt.Color(255, 255, 255));
        birthDatejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        birthDatejLabel.setText("Data de naixement");

        sexejLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sexejLabel.setForeground(new java.awt.Color(255, 255, 255));
        sexejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sexejLabel.setText("Sexe");

        townjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        townjLabel.setForeground(new java.awt.Color(255, 255, 255));
        townjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        townjLabel.setText("Població");

        telfjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        telfjLabel.setForeground(new java.awt.Color(255, 255, 255));
        telfjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        telfjLabel.setText("Telefon");

        mailjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mailjLabel.setForeground(new java.awt.Color(255, 255, 255));
        mailjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mailjLabel.setText("Email");

        fedejCheckBox.setBackground(new java.awt.Color(0, 153, 204));
        fedejCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fedejCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        fedejCheckBox.setText("Federat");
        fedejCheckBox.setBorder(null);
        fedejCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fedejCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        fedejCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fedejCheckBoxStateChanged(evt);
            }
        });

        javax.swing.GroupLayout titlesjPanelLayout = new javax.swing.GroupLayout(titlesjPanel);
        titlesjPanel.setLayout(titlesjPanelLayout);
        titlesjPanelLayout.setHorizontalGroup(
            titlesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlesjPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(titlesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mailjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telfjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(townjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthDatejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cognomsjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DNIjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(titlesjPanelLayout.createSequentialGroup()
                        .addComponent(fedejCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        titlesjPanelLayout.setVerticalGroup(
            titlesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlesjPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(DNIjLabel)
                .addGap(41, 41, 41)
                .addComponent(namejLabel)
                .addGap(41, 41, 41)
                .addComponent(cognomsjLabel)
                .addGap(41, 41, 41)
                .addComponent(birthDatejLabel)
                .addGap(41, 41, 41)
                .addComponent(sexejLabel)
                .addGap(41, 41, 41)
                .addComponent(townjLabel)
                .addGap(41, 41, 41)
                .addComponent(telfjLabel)
                .addGap(41, 41, 41)
                .addComponent(mailjLabel)
                .addGap(41, 41, 41)
                .addComponent(fedejCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        valuesjPanel.setBackground(new java.awt.Color(204, 255, 255));
        valuesjPanel.setPreferredSize(new java.awt.Dimension(490, 680));

        DNIjTextField.setForeground(new java.awt.Color(204, 204, 204));
        DNIjTextField.setText("00000000A");

        fedejTextField.setText("Entitat");
        fedejTextField.setEnabled(false);

        birthDatejSpinner.setModel(new javax.swing.SpinnerDateModel());

        sexejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Home", "Dona" }));

        acceptjButton.setText("Acceptar");
        acceptjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptjButtonActionPerformed(evt);
            }
        });

        canceljButton.setText("Cancelar");
        canceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceljButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout valuesjPanelLayout = new javax.swing.GroupLayout(valuesjPanel);
        valuesjPanel.setLayout(valuesjPanelLayout);
        valuesjPanelLayout.setHorizontalGroup(
            valuesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valuesjPanelLayout.createSequentialGroup()
                .addGroup(valuesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(valuesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, valuesjPanelLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(valuesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fedejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(telfjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(townjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cognomsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DNIjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(valuesjPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(valuesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(birthDatejSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sexejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(valuesjPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(acceptjButton)
                        .addGap(102, 102, 102)
                        .addComponent(canceljButton)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        valuesjPanelLayout.setVerticalGroup(
            valuesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valuesjPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(DNIjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(cognomsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(birthDatejSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(sexejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(townjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(telfjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(mailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(fedejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(valuesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptjButton)
                    .addComponent(canceljButton))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(titlesjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(valuesjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlesjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(valuesjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptjButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_acceptjButtonActionPerformed

    private void canceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceljButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_canceljButtonActionPerformed

    private void fedejCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fedejCheckBoxStateChanged
        // TODO add your handling code here:
        if (fedejCheckBox.isSelected()) {
            fedejTextField.setEnabled(true);
        } else {
            fedejTextField.setEnabled(false);
        }
    }//GEN-LAST:event_fedejCheckBoxStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DNIjLabel;
    private javax.swing.JTextField DNIjTextField;
    private javax.swing.JButton acceptjButton;
    private javax.swing.JLabel birthDatejLabel;
    private javax.swing.JSpinner birthDatejSpinner;
    private javax.swing.JButton canceljButton;
    private javax.swing.JLabel cognomsjLabel;
    private javax.swing.JTextField cognomsjTextField;
    private javax.swing.JCheckBox fedejCheckBox;
    private javax.swing.JTextField fedejTextField;
    private javax.swing.JLabel mailjLabel;
    private javax.swing.JTextField mailjTextField;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JComboBox<String> sexejComboBox;
    private javax.swing.JLabel sexejLabel;
    private javax.swing.JLabel telfjLabel;
    private javax.swing.JTextField telfjTextField;
    private javax.swing.JPanel titlesjPanel;
    private javax.swing.JLabel townjLabel;
    private javax.swing.JTextField townjTextField;
    private javax.swing.JPanel valuesjPanel;
    // End of variables declaration//GEN-END:variables
}
