/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package cem.view.dialogsMenu2;

import cem.controller.Controller;
import cem.enums.Sexe;
import cem.exceptions.AdditionException;
import cem.exceptions.CorredoresException;
import cem.model.Participant;
import java.awt.Color;
import java.awt.event.*;
import java.sql.SQLException;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class RegisterParticipantDialog1 extends javax.swing.JDialog {

    private Controller controller;
    private boolean modifier = false;
    private String dni_res;
    /**
     * Creates new form RegisterParticipantDialog
     */
    public RegisterParticipantDialog1(java.awt.Frame parent, boolean modal, String dni) {
        super(parent, modal);
        setTitle("Registrar participant");
        setModal(true);
        setResizable(false);
        initComponents();
        setLocationRelativeTo(null);
        controller = Controller.getInstance();
        if (dni != null){
            try{
            Participant chosen = controller.getParticipant(dni);
            DNIjTextField.setText(dni);
            namejTextField.setText(chosen.getNom());
            cognomsjTextField.setText(chosen.getCognoms());
            townjTextField.setText(chosen.getPoblacio());
            telfjTextField.setText(chosen.getNumTelefon());
            mailjTextField.setText(chosen.getEmail());
            DNIjLabel.setEnabled(false);
            modifier = true;
            dni_res = dni; 
            }catch(AdditionException e){
                System.out.println("Este error no se debe dar en esta circunstancia " + e.getMessage());
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlesjPanel = new javax.swing.JPanel();
        DNIjLabel = new javax.swing.JLabel();
        namejLabel = new javax.swing.JLabel();
        cognomsjLabel = new javax.swing.JLabel();
        birthDatejLabel = new javax.swing.JLabel();
        sexejLabel = new javax.swing.JLabel();
        townjLabel = new javax.swing.JLabel();
        telfjLabel = new javax.swing.JLabel();
        mailjLabel = new javax.swing.JLabel();
        fedejCheckBox = new javax.swing.JCheckBox();
        valuesjPanel = new javax.swing.JPanel();
        DNIjTextField = new javax.swing.JTextField();
        namejTextField = new javax.swing.JTextField();
        cognomsjTextField = new javax.swing.JTextField();
        townjTextField = new javax.swing.JTextField();
        telfjTextField = new javax.swing.JTextField();
        mailjTextField = new javax.swing.JTextField();
        fedejTextField = new javax.swing.JTextField();
        sexejComboBox = new javax.swing.JComboBox<>();
        acceptjButton = new javax.swing.JButton();
        canceljButton = new javax.swing.JButton();
        bornDateDatePicker1 = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titlesjPanel.setBackground(new java.awt.Color(0, 153, 204));

        DNIjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DNIjLabel.setText("DNI/NIF");
        DNIjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DNIjLabel.setForeground(new java.awt.Color(255, 255, 255));

        namejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namejLabel.setText("Nom");
        namejLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namejLabel.setForeground(new java.awt.Color(255, 255, 255));

        cognomsjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cognomsjLabel.setText("Cognoms");
        cognomsjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cognomsjLabel.setForeground(new java.awt.Color(255, 255, 255));

        birthDatejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        birthDatejLabel.setText("Data de naixement");
        birthDatejLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        birthDatejLabel.setForeground(new java.awt.Color(255, 255, 255));

        sexejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sexejLabel.setText("Sexe");
        sexejLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sexejLabel.setForeground(new java.awt.Color(255, 255, 255));

        townjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        townjLabel.setText("Població");
        townjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        townjLabel.setForeground(new java.awt.Color(255, 255, 255));

        telfjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        telfjLabel.setText("Telefon");
        telfjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        telfjLabel.setForeground(new java.awt.Color(255, 255, 255));

        mailjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mailjLabel.setText("Email");
        mailjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mailjLabel.setForeground(new java.awt.Color(255, 255, 255));

        fedejCheckBox.setText("Federat");
        fedejCheckBox.setBackground(new java.awt.Color(0, 153, 204));
        fedejCheckBox.setBorder(null);
        fedejCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fedejCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        fedejCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fedejCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        fedejCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fedejCheckBoxStateChanged(evt);
            }
        });

        javax.swing.GroupLayout titlesjPanelLayout = new javax.swing.GroupLayout(titlesjPanel);
        titlesjPanel.setLayout(titlesjPanelLayout);
        titlesjPanelLayout.setHorizontalGroup(
            titlesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlesjPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(titlesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mailjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telfjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(townjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthDatejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cognomsjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DNIjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(titlesjPanelLayout.createSequentialGroup()
                        .addComponent(fedejCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        titlesjPanelLayout.setVerticalGroup(
            titlesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlesjPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(DNIjLabel)
                .addGap(41, 41, 41)
                .addComponent(namejLabel)
                .addGap(41, 41, 41)
                .addComponent(cognomsjLabel)
                .addGap(41, 41, 41)
                .addComponent(birthDatejLabel)
                .addGap(41, 41, 41)
                .addComponent(sexejLabel)
                .addGap(41, 41, 41)
                .addComponent(townjLabel)
                .addGap(41, 41, 41)
                .addComponent(telfjLabel)
                .addGap(41, 41, 41)
                .addComponent(mailjLabel)
                .addGap(41, 41, 41)
                .addComponent(fedejCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        valuesjPanel.setBackground(new java.awt.Color(204, 255, 255));
        valuesjPanel.setPreferredSize(new java.awt.Dimension(490, 680));

        DNIjTextField.setText("00000000A");
        DNIjTextField.setForeground(new java.awt.Color(204, 204, 204));
        DNIjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DNIjTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DNIjTextFieldFocusLost(evt);
            }
        });
        DNIjTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DNIjTextFieldMouseClicked(evt);
            }
        });

        telfjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                telfjTextFieldFocusLost(evt);
            }
        });

        mailjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailjTextFieldFocusLost(evt);
            }
        });

        fedejTextField.setText("Entitat");
        fedejTextField.setEnabled(false);
        fedejTextField.setForeground(new java.awt.Color(204, 204, 204));
        fedejTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fedejTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fedejTextFieldFocusLost(evt);
            }
        });
        fedejTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fedejTextFieldMouseClicked(evt);
            }
        });

        sexejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Home", "Dona" }));

        acceptjButton.setText("Acceptar");
        acceptjButton.setEnabled(false);
        acceptjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptjButtonActionPerformed(evt);
            }
        });

        canceljButton.setText("Cancelar");
        canceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceljButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout valuesjPanelLayout = new javax.swing.GroupLayout(valuesjPanel);
        valuesjPanel.setLayout(valuesjPanelLayout);
        valuesjPanelLayout.setHorizontalGroup(
            valuesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valuesjPanelLayout.createSequentialGroup()
                .addGroup(valuesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(valuesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, valuesjPanelLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(valuesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fedejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(telfjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(townjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cognomsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DNIjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(valuesjPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(valuesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sexejComboBox, 0, 338, Short.MAX_VALUE)
                                .addComponent(bornDateDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(valuesjPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(acceptjButton)
                        .addGap(102, 102, 102)
                        .addComponent(canceljButton)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        valuesjPanelLayout.setVerticalGroup(
            valuesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valuesjPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(DNIjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(cognomsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(bornDateDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(sexejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(townjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(telfjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(mailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(fedejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(valuesjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptjButton)
                    .addComponent(canceljButton))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(titlesjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(valuesjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlesjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(valuesjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptjButtonActionPerformed
        try{
            String dni = DNIjTextField.getText();
            String nom = namejLabel.getText();
            String cognom = cognomsjLabel.getText();
            LocalDate neix = bornDateDatePicker1.getDate();
            String town = townjTextField.getText();
            String tlf = telfjTextField.getText();
            String email = mailjTextField.getText();
            boolean sex;
            if (sexejComboBox.getSelectedIndex() == 0) sex = true;
            else sex = false;
            String entitat = null;
            if (fedejCheckBox.isEnabled()){
                entitat = fedejTextField.getText();
            }
            Participant pr = new Participant(dni,nom,cognom,neix,sex,town,tlf,email,entitat,fedejCheckBox.isEnabled()); 
            if (!modifier){
            controller.addParticipant(pr);
            }else{
                controller.modifiParticipant(pr);
            }
        }catch(AdditionException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }catch(SQLException e){
            System.out.println("Este error no se deberia dar: " + e.getMessage());
            
        }
        dispose();
        
        /*
        
        boolean ok = true;
        String textoAMostrar = "Error";
        if (!controller.validateNif(DNIjTextField.getText())) {
            ok = false;
            textoAMostrar = "DNI Invalido";
        } else if (!controller.validateTlf(telfjTextField.getText())) {
            ok = false;
            textoAMostrar = "Telefon Malament";
        } else if (!controller.validateEmail(mailjTextField.getText())) {
            ok = false;
            textoAMostrar = "Email malament";
        } else {
            String dni = DNIjTextField.getText();
            String nom = namejTextField.getText();
            String cognom = cognomsjTextField.getText();
            Instant instant = ((Date) birthDatejSpinner.getValue()).toInstant();
            LocalDate nacimiento = instant.atZone(ZoneId.systemDefault()).toLocalDate();
            String sexe = (String) sexejComboBox.getSelectedItem();
            String poblacio = townjTextField.getText();
            String tel = telfjTextField.getText();
            String mail = mailjTextField.getText();
            Boolean fede = fedejCheckBox.isEnabled();
            //String entitat = fede ? fednamejTextFieldejTextField.getText() : "";

            try {
                controller.addParticipant(new Participant(dni, nom, cognom, nacimiento, sexe, poblacio, tel, mail, entitat, fede));
            } catch (CorredoresException ex) {
                System.out.println(ex.getMessage());
            } catch (AdditionException ex) {
                System.out.println(ex.getMessage());
            }

        }
        if (!ok) {
            JOptionPane.showMessageDialog(this, textoAMostrar, "Error", JOptionPane.ERROR_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(this, "Participant Registrat!", "Registrat!", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }

        //dispose();
*/
    }//GEN-LAST:event_acceptjButtonActionPerformed

    private void canceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceljButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_canceljButtonActionPerformed

    private void fedejCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fedejCheckBoxStateChanged
        // TODO add your handling code here:
        if (fedejCheckBox.isSelected()) {
            fedejTextField.setEnabled(true);
        } else {
            fedejTextField.setEnabled(false);
        }
    }//GEN-LAST:event_fedejCheckBoxStateChanged

    private void DNIjTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DNIjTextFieldMouseClicked
        // TODO add your handling code here:
        if (DNIjTextField.getText().equals("00000000A") && !modifier) {
            DNIjTextField.setText("");
            DNIjTextField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_DNIjTextFieldMouseClicked
    /*
    private void DNIjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DNIjTextFieldFocusLost
        // TODO add your handling code here:
        if (DNIjTextField.getText().isEmpty()) {
                DNIjTextField.setForeground(Color.GRAY);
                DNIjTextField.setText("00000000A");
        }
        DNIjTextField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String texto = DNIjTextField.getText();
                if (!texto.equals("00000000A") && !texto.isEmpty()) {
                    boolean esValido = controller.validateNif(texto);
                    DNIjTextField.setBackground(esValido ? Color.GREEN : Color.PINK);
                } else {
                    DNIjTextField.setBackground(Color.WHITE);
                }
            }
    }                                             
    
    private void canceljButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        dispose();
    }                                             

    private void fedejCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {                                           
        // TODO add your handling code here:
        if (fedejCheckBox.isSelected()) {
            fedejTextField.setEnabled(true);
        } else {
            fedejTextField.setEnabled(false);
        }
    }                                          

    private void DNIjTextFieldMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
        if (DNIjTextField.getText().equals("00000000A")) {
            DNIjTextField.setText("");
            DNIjTextField.setForeground(Color.BLACK);
        }
    }                                          
    /*
    private void DNIjTextFieldFocusLost(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
        if (DNIjTextField.getText().isEmpty()) {
                DNIjTextField.setForeground(Color.GRAY);
                DNIjTextField.setText("00000000A");
        }
        DNIjTextField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String texto = DNIjTextField.getText();
                if (!texto.equals("00000000A") && !texto.isEmpty()) {
                    boolean esValido = controller.validateNif(texto);
                    DNIjTextField.setBackground(esValido ? Color.GREEN : Color.PINK);
                } else {
                    DNIjTextField.setBackground(Color.WHITE);
                }
            }
        });
    }//GEN-LAST:event_DNIjTextFieldFocusLost
*/
    private void DNIjTextFieldFocusLost(java.awt.event.FocusEvent evt) {
        // TODO add your handling code here:
        if (!modifier) {
            if (DNIjTextField.getText().isEmpty()) {
                DNIjTextField.setForeground(Color.GRAY);
                DNIjTextField.setBackground(Color.WHITE);
                DNIjTextField.setText("00000000A");
            } else {

                String texto = DNIjTextField.getText();
                boolean esValido = controller.validateNif(texto);
                DNIjTextField.setBackground(esValido ? Color.GREEN : Color.PINK);
                checkbotones();
            }
        }else{
            DNIjTextField.setText(dni_res);
            
        }
    }
    
    private void checkbotones(){
        boolean aprobate;
        if (!modifier) {
            if (controller.validateNif(DNIjTextField.getText()) && controller.validateEmail(mailjTextField.getText()) && controller.validateTlf(telfjTextField.getText())
                    && !namejTextField.getText().isEmpty() && !cognomsjTextField.getText().isEmpty() && !townjTextField.getText().isEmpty()) {
                acceptjButton.setEnabled(true);
            } else {
                acceptjButton.setEnabled(false);
            }
        }else{
            if (controller.validateEmail(mailjTextField.getText()) && controller.validateTlf(telfjTextField.getText())
                    && !namejTextField.getText().isEmpty() && !cognomsjTextField.getText().isEmpty() && !townjTextField.getText().isEmpty()){
                acceptjButton.setEnabled(true);
            } else {
                acceptjButton.setEnabled(false);
            }
            
            
        }
        
    }
    
    
    


    private void DNIjTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DNIjTextFieldFocusGained
        // TODO add your handling code here:
        if (DNIjTextField.getText().equals("00000000A")) {
            DNIjTextField.setText("");
            DNIjTextField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_DNIjTextFieldFocusGained

    private void fedejTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fedejTextFieldMouseClicked
        // TODO add your handling code here:
        if (fedejTextField.getText().equals("Entitat")) {
            fedejTextField.setText("");
            fedejTextField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_fedejTextFieldMouseClicked

    private void fedejTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fedejTextFieldFocusGained
        // TODO add your handling code here:
        if (fedejTextField.getText().equals("Entitat")) {
            fedejTextField.setText("");
            fedejTextField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_fedejTextFieldFocusGained

    private void fedejTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fedejTextFieldFocusLost
        // TODO add your handling code here:

        if (fedejTextField.getText().isEmpty()) {
            fedejTextField.setForeground(Color.GRAY);
            fedejTextField.setText("Entitat");
        }
    }//GEN-LAST:event_fedejTextFieldFocusLost

    private void telfjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telfjTextFieldFocusLost
        if (!controller.validateTlf(telfjTextField.getText())){
            telfjTextField.setBackground(Color.PINK);
        }else{
            telfjTextField.setBackground(Color.GREEN);
            checkbotones();
        }
    }//GEN-LAST:event_telfjTextFieldFocusLost

    private void mailjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailjTextFieldFocusLost
        if (!controller.validateEmail(mailjTextField.getText())){
            mailjTextField.setBackground(Color.PINK);
        }else{
            mailjTextField.setBackground(Color.GREEN);
            checkbotones();
        }
    }//GEN-LAST:event_mailjTextFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DNIjLabel;
    private javax.swing.JTextField DNIjTextField;
    private javax.swing.JButton acceptjButton;
    private javax.swing.JLabel birthDatejLabel;
    private com.github.lgooddatepicker.components.DatePicker bornDateDatePicker1;
    private javax.swing.JButton canceljButton;
    private javax.swing.JLabel cognomsjLabel;
    private javax.swing.JTextField cognomsjTextField;
    private javax.swing.JCheckBox fedejCheckBox;
    private javax.swing.JTextField fedejTextField;
    private javax.swing.JLabel mailjLabel;
    private javax.swing.JTextField mailjTextField;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JComboBox<String> sexejComboBox;
    private javax.swing.JLabel sexejLabel;
    private javax.swing.JLabel telfjLabel;
    private javax.swing.JTextField telfjTextField;
    private javax.swing.JPanel titlesjPanel;
    private javax.swing.JLabel townjLabel;
    private javax.swing.JTextField townjTextField;
    private javax.swing.JPanel valuesjPanel;
    // End of variables declaration//GEN-END:variables
}
