/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package cem.view.dialogsMenu2;

import cem.controller.Controller;
import cem.exceptions.AdditionException;
import cem.model.Participant;

/**
 *
 * @author joellopez
 */
public class ThingsParticipant extends javax.swing.JDialog {

    /**
     * Creates new form ThingsParticipant
     */
    
    private Participant pa;
    private Controller controller;
    
    public ThingsParticipant(java.awt.Frame parent, boolean modal, String nif) {
        super(parent, modal);
        initComponents();
        controller = Controller.getInstance();
        try{
        pa = controller.getParticipant(nif);
        putThings();
        }catch (AdditionException e){
            System.out.println("Aqui nunca debe llegar ");
        }
    }
    
    private void putThings(){
        nif_i.setText(pa.getNif());
        nom_i.setText(pa.getNom());
        cog_i.setText(pa.getCognoms());
        se_i.setText(pa.isSexe() ?  "Home": "Dona");
        te_i.setText(pa.getNumTelefon());
        po_i.setText(pa.getPoblacio());
        ge_i.setText(pa.getEmail());
        if (pa.getEntitat() != null) ent_i.setText(pa.getEntitat());
        else ent_i.setText("X");
        if (pa.getObservacions() != null) jLabel23.setText(pa.getObservacions());
        else jLabel23.setText("X");
        nif.setText(pa.getNif());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nif = new javax.swing.JLabel();
        textprinc1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nif_i = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cog_i = new javax.swing.JLabel();
        nei_i = new javax.swing.JLabel();
        se_i = new javax.swing.JLabel();
        nom_i = new javax.swing.JLabel();
        te_i = new javax.swing.JLabel();
        po_i = new javax.swing.JLabel();
        ge_i = new javax.swing.JLabel();
        ent_i = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("jLabel1");

        jLabel9.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("jLabel1");

        jLabel20.setBackground(new java.awt.Color(102, 102, 102));
        jLabel20.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        nif.setFont(new java.awt.Font("Fira Code", 1, 18)); // NOI18N
        nif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nif.setText("nif");

        textprinc1.setFont(new java.awt.Font("Fira Code", 1, 18)); // NOI18N
        textprinc1.setText("Dades Participant:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textprinc1)
                    .addComponent(nif, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(textprinc1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nif)
                .addGap(33, 33, 33))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NIF:");

        jLabel3.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nom:");

        jLabel4.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cognom:");

        jLabel5.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Neixement:");

        jLabel6.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Sexe:");

        jLabel7.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Poblacio:");

        nif_i.setBackground(new java.awt.Color(102, 102, 102));
        nif_i.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        nif_i.setForeground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Telefon:");

        jLabel11.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Gmail:");

        jLabel12.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("observacions:");

        jLabel13.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Entitat:");

        cog_i.setBackground(new java.awt.Color(102, 102, 102));
        cog_i.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        cog_i.setForeground(new java.awt.Color(0, 0, 0));
        cog_i.setText("jLabel1");

        nei_i.setBackground(new java.awt.Color(102, 102, 102));
        nei_i.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        nei_i.setForeground(new java.awt.Color(0, 0, 0));
        nei_i.setText("jLabel1");

        se_i.setBackground(new java.awt.Color(102, 102, 102));
        se_i.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        se_i.setForeground(new java.awt.Color(0, 0, 0));
        se_i.setText("jLabel1");

        nom_i.setBackground(new java.awt.Color(102, 102, 102));
        nom_i.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        nom_i.setForeground(new java.awt.Color(0, 0, 0));
        nom_i.setText("jLabel1");

        te_i.setBackground(new java.awt.Color(102, 102, 102));
        te_i.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        te_i.setForeground(new java.awt.Color(0, 0, 0));
        te_i.setText("jLabel1");

        po_i.setBackground(new java.awt.Color(102, 102, 102));
        po_i.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        po_i.setForeground(new java.awt.Color(0, 0, 0));
        po_i.setText("jLabel1");

        ge_i.setBackground(new java.awt.Color(102, 102, 102));
        ge_i.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        ge_i.setForeground(new java.awt.Color(0, 0, 0));
        ge_i.setText("jLabel1");

        ent_i.setBackground(new java.awt.Color(102, 102, 102));
        ent_i.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        ent_i.setForeground(new java.awt.Color(0, 0, 0));
        ent_i.setText("jLabel1");

        jLabel23.setBackground(new java.awt.Color(102, 102, 102));
        jLabel23.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ent_i))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ge_i))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(te_i))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(po_i))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nif_i, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cog_i, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nei_i, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(se_i, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nom_i, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(52, 52, 52))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nif_i))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nom_i))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cog_i))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nei_i))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(se_i))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(po_i))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(te_i))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ge_i))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ent_i))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cog_i;
    private javax.swing.JLabel ent_i;
    private javax.swing.JLabel ge_i;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nei_i;
    private javax.swing.JLabel nif;
    private javax.swing.JLabel nif_i;
    private javax.swing.JLabel nom_i;
    private javax.swing.JLabel po_i;
    private javax.swing.JLabel se_i;
    private javax.swing.JLabel te_i;
    private javax.swing.JLabel textprinc1;
    // End of variables declaration//GEN-END:variables
}
