/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package cem.view.dialogsMenu2.subMenuMarxes;

import cem.controller.Controller;
import cem.exceptions.AdditionException;
import cem.model.Inscripcio;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ivang
 */
public class InscriureParticipantDialog1 extends javax.swing.JDialog {

    //atributos
    private Controller controller;
    private String edicio;
    private boolean modifier = false;

    /**
     * Creates new form InscriureParticipantDialog1
     */
    
    //contrucor
    public InscriureParticipantDialog1(java.awt.Frame parent, boolean modal, String dni, String edicio) {
        super(parent, modal);
        initComponents();
        controller = Controller.getInstance();
        this.edicio = edicio;
        jLabelAny.setText(edicio);
        
        //si el dni no es null hace las siguientes cosas
        if (dni != null) {
            try {
                Inscripcio chosen = controller.getInscripcio(dni, edicio);
                if (chosen != null) {
                    jTextFieldDNI.setText(dni);
                    //jLabelEdicio.setText(edicio);
                    modifier = true;
                    jTextFieldDNI.setEditable(false);
                    jButtonRegistrar.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Inscripció no trobada."); // lo tenia puesto porque no devolvia null
                    //queria ver si el fallo era aqui y si era
                }
            } catch (AdditionException e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            }
        } else {
            jButtonModificar.setVisible(false);
            jButtonModificar.setEnabled(false);
            jLabelAsistencia.setVisible(false);
            jComboBoxAsistencia.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelModalitat = new javax.swing.JLabel();
        jLabelAsistencia = new javax.swing.JLabel();
        jLabelNif = new javax.swing.JLabel();
        jLabelDorsal1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSpinnerDorsal = new javax.swing.JSpinner();
        jComboBoxModalitat = new javax.swing.JComboBox<>();
        jTextFieldDNI = new javax.swing.JTextField();
        jButtonSortir = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jComboBoxAsistencia = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabelEdicio = new javax.swing.JLabel();
        jLabelAny = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabelModalitat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelModalitat.setText("MODALITAT");

        jLabelAsistencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAsistencia.setText("ASISTÈNCIA");

        jLabelNif.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNif.setText("DNI / NIF PARTICIPANT");

        jLabelDorsal1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDorsal1.setText("DORSAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabelModalitat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNif)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelAsistencia)
                        .addGap(106, 106, 106))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(134, Short.MAX_VALUE)
                    .addComponent(jLabelDorsal1)
                    .addGap(120, 120, 120)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelModalitat)
                .addGap(45, 45, 45)
                .addComponent(jLabelNif)
                .addGap(36, 36, 36)
                .addComponent(jLabelAsistencia)
                .addGap(116, 116, 116))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(jLabelDorsal1)
                    .addContainerGap(292, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jSpinnerDorsal.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9999, 1));

        jComboBoxModalitat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Llarga", "Curta" }));

        jTextFieldDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDNIActionPerformed(evt);
            }
        });
        jTextFieldDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDNIKeyReleased(evt);
            }
        });

        jButtonSortir.setText("Sortir");
        jButtonSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortirActionPerformed(evt);
            }
        });

        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jComboBoxAsistencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ha abandonat", "Desqualificat" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jButtonModificar)
                .addGap(34, 34, 34)
                .addComponent(jButtonRegistrar)
                .addGap(57, 57, 57)
                .addComponent(jButtonSortir)
                .addGap(56, 56, 56))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSpinnerDorsal, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(jTextFieldDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(jComboBoxModalitat, 0, 270, Short.MAX_VALUE)
                    .addComponent(jComboBoxAsistencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jSpinnerDorsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jComboBoxModalitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jComboBoxAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSortir)
                    .addComponent(jButtonRegistrar)
                    .addComponent(jButtonModificar))
                .addGap(21, 21, 21))
        );

        jPanel3.setBackground(new java.awt.Color(0, 152, 204));

        jLabelEdicio.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabelEdicio.setText("EDICIO");

        jLabelAny.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jLabelAny)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEdicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEdicio)
                    .addComponent(jLabelAny))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDNIActionPerformed
        //  NADA
    }//GEN-LAST:event_jTextFieldDNIActionPerformed

    //boton salir
    private void jButtonSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSortirActionPerformed
        dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSortirActionPerformed

    
    //boton que coge los datos que pone el usuario para añadirlo a la base de datos (inscripcion)
    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        try {
            int dorsal = (int) jSpinnerDorsal.getValue();
            boolean modalitat;
            if (jComboBoxModalitat.getSelectedIndex() == 0) {
                modalitat = true;
            } else {
                modalitat = false;
            }
            String asistencia = "No ha vingut";
            String dni = jTextFieldDNI.getText();
            Inscripcio i = new Inscripcio(dorsal, modalitat, asistencia, dni, Integer.parseInt(edicio));
            if (!controller.existParticipantforDNI(dni)) {
                JOptionPane.showMessageDialog(this, "Aquest participant no està registrat", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (controller.existParticipantinInscripcio(dni, Integer.parseInt(edicio))) {
                JOptionPane.showMessageDialog(this, "Aquest participant ja està registrat en una cursa d'aquesta edició", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (controller.existDorsal(dorsal, Integer.parseInt(edicio))) {
                JOptionPane.showMessageDialog(this, "Aquest dorsal ja està utilitzat en aquesta cursa", "Dorsa Repetit", JOptionPane.ERROR_MESSAGE);
            } else {
                if (!modifier) {
                    controller.addInscripcio(i);
                }
                JOptionPane.showMessageDialog(this, "S'ha afegit correctament aquesta inscripcio", "Afegit", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
        } catch (AdditionException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            System.out.println("Este error no se deberia dar: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    //valida que las cosas esten bien
    private void jTextFieldDNIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIKeyReleased
        if (jTextFieldDNI.getText().isEmpty()) {
            jTextFieldDNI.setForeground(Color.GRAY);
            jTextFieldDNI.setBackground(Color.WHITE);
            jTextFieldDNI.setText("00000000A");
        } else {
            String texto = jTextFieldDNI.getText();
            boolean esValido = controller.validateNif(texto);
            jTextFieldDNI.setBackground(esValido ? Color.GREEN : Color.PINK);
            if (esValido) {
                jButtonRegistrar.setEnabled(true);
            } else {
                jButtonRegistrar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jTextFieldDNIKeyReleased

    //boton que sirve para modificar los datos de la inscripcion siemre que esten los datos bien
    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        try {
            int dorsal = (int) jSpinnerDorsal.getValue();
            boolean modalitat;
            if (jComboBoxModalitat.getSelectedIndex() == 0) {
                modalitat = true;
            } else {
                modalitat = false;
            }
            String asistencia;
            if (jComboBoxAsistencia.getSelectedIndex() == 0) {
                asistencia = "No ha vingut";
            } else {
                asistencia = (String) jComboBoxAsistencia.getSelectedItem();
            }
            String dni = jTextFieldDNI.getText();
            Inscripcio i = new Inscripcio(dorsal, modalitat, asistencia, dni, Integer.parseInt(edicio));
            if (controller.existDorsal(dorsal, Integer.parseInt(edicio))) {
                JOptionPane.showMessageDialog(this, "Aquest dorsal ja està utilitzat en aquesta cursa", "Dorsa Repetit", JOptionPane.ERROR_MESSAGE);
            } else {
                controller.modifiInscripcio(i);
                JOptionPane.showMessageDialog(this, "S'ha modificat correctament aquesta inscripcio", "Modificat", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
        } catch (SQLException e) {
            System.out.println("Este error no se deberia dar: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonSortir;
    private javax.swing.JComboBox<String> jComboBoxAsistencia;
    private javax.swing.JComboBox<String> jComboBoxModalitat;
    private javax.swing.JLabel jLabelAny;
    private javax.swing.JLabel jLabelAsistencia;
    private javax.swing.JLabel jLabelDorsal1;
    private javax.swing.JLabel jLabelEdicio;
    private javax.swing.JLabel jLabelModalitat;
    private javax.swing.JLabel jLabelNif;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpinnerDorsal;
    private javax.swing.JTextField jTextFieldDNI;
    // End of variables declaration//GEN-END:variables
}
