/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package cem.view.dialogsMenu2.subMenuMarxes;

import cem.view.dialogsMenu2.ChoseParticipant;
import java.sql.SQLException;

/**
 *
 * @author admin
 */
public class MarxesDialog1 extends javax.swing.JDialog {

    private InscriureParticipantDialog1 inscriureParticipant;
    private String edicio;

    /**
     * Creates new form MarxesDialog1
     */
    public MarxesDialog1(java.awt.Frame parent, boolean modal, String edicio) {
        super(parent, modal);
        initComponents();
        ediciojLabel.setText(edicio);
        this.edicio = edicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ediciojPanel = new javax.swing.JPanel();
        textEdiciojLabel = new javax.swing.JLabel();
        ediciojLabel = new javax.swing.JLabel();
        buttonsjPanel = new javax.swing.JPanel();
        jButtonInscriureParticipant = new javax.swing.JButton();
        jButtonEditarInscripció = new javax.swing.JButton();
        jButtonSortida = new javax.swing.JButton();
        jButtonArribada = new javax.swing.JButton();
        jButtonSortit = new javax.swing.JButton();
        jButtonStats = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ediciojPanel.setBackground(new java.awt.Color(0, 153, 204));

        textEdiciojLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        textEdiciojLabel.setText("EDICIÓ");

        ediciojLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N

        javax.swing.GroupLayout ediciojPanelLayout = new javax.swing.GroupLayout(ediciojPanel);
        ediciojPanel.setLayout(ediciojPanelLayout);
        ediciojPanelLayout.setHorizontalGroup(
            ediciojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ediciojPanelLayout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(textEdiciojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ediciojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );
        ediciojPanelLayout.setVerticalGroup(
            ediciojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ediciojPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(ediciojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEdiciojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ediciojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        textEdiciojLabel.setForeground(new java.awt.Color(255, 255, 255));
        ediciojLabel.setForeground(new java.awt.Color(255, 255, 255));

        buttonsjPanel.setBackground(new java.awt.Color(204, 255, 255));

        jButtonInscriureParticipant.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonInscriureParticipant.setText("Inscriure participant");
        jButtonInscriureParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInscriureParticipantActionPerformed(evt);
            }
        });

        jButtonEditarInscripció.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonEditarInscripció.setText("Editar inscripció");
        jButtonEditarInscripció.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarInscripcióActionPerformed(evt);
            }
        });

        jButtonSortida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSortida.setText("Sortida");
        jButtonSortida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortidaActionPerformed(evt);
            }
        });

        jButtonArribada.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonArribada.setText("Arribada");
        jButtonArribada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArribadaActionPerformed(evt);
            }
        });

        jButtonSortit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonSortit.setText("Sortir");
        jButtonSortit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortitActionPerformed(evt);
            }
        });

        jButtonStats.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonStats.setText("Estaditiques");
        jButtonStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonsjPanelLayout = new javax.swing.GroupLayout(buttonsjPanel);
        buttonsjPanel.setLayout(buttonsjPanelLayout);
        buttonsjPanelLayout.setHorizontalGroup(
            buttonsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSortit, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(buttonsjPanelLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(buttonsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonStats, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonArribada, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSortida, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditarInscripció, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInscriureParticipant, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        buttonsjPanelLayout.setVerticalGroup(
            buttonsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsjPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButtonInscriureParticipant, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEditarInscripció, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSortida, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonArribada, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonStats, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButtonSortit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ediciojPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonsjPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ediciojPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonsjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //boton salir
    private void jButtonSortitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSortitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSortitActionPerformed

    //abre un JDialog de InscriureParticipant
    private void jButtonInscriureParticipantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInscriureParticipantActionPerformed
        inscriureParticipant = new InscriureParticipantDialog1(null, true, null, edicio); // lo pongo null porque se que la maria dijo que se pone null o el padre del padre
        setVisible(false);
        inscriureParticipant.setLocationRelativeTo(this);
        inscriureParticipant.setVisible(true);
        setVisible(true);
    }//GEN-LAST:event_jButtonInscriureParticipantActionPerformed
    //abre un JDialog de CoseParticiànt
    private void jButtonEditarInscripcióActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarInscripcióActionPerformed
        ChoseParticipants window = new ChoseParticipants(null, true, edicio);
        setVisible(false);
        window.setLocationRelativeTo(this);
        window.setVisible(true);
        setVisible(true);    }//GEN-LAST:event_jButtonEditarInscripcióActionPerformed

    //abre un JDialog de rankingInscripcionsMarxa
    private void jButtonStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStatsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        RankingInscripcionsMarxa rankingInscripcionsMarxa;
        try {
            rankingInscripcionsMarxa = new RankingInscripcionsMarxa(null, true, edicio);
            rankingInscripcionsMarxa.setLocationRelativeTo(this);
            rankingInscripcionsMarxa.setVisible(true);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        this.setVisible(true);
    }//GEN-LAST:event_jButtonStatsActionPerformed

    // abre un JDialog de PosarTEmps
    private void jButtonSortidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSortidaActionPerformed
        PosarTemps ps = new PosarTemps(null, true, true, edicio);
        setVisible(false);
        ps.setLocationRelativeTo(this);
        ps.setVisible(true);
        setVisible(true);
    }//GEN-LAST:event_jButtonSortidaActionPerformed

    // abre un JDialog de PosarTEmps
    private void jButtonArribadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArribadaActionPerformed
        PosarTemps ps = new PosarTemps(null, true, false, edicio);
        setVisible(false);
        ps.setLocationRelativeTo(this);
        ps.setVisible(true);
        setVisible(true);
    }//GEN-LAST:event_jButtonArribadaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsjPanel;
    private javax.swing.JLabel ediciojLabel;
    private javax.swing.JPanel ediciojPanel;
    private javax.swing.JButton jButtonArribada;
    private javax.swing.JButton jButtonEditarInscripció;
    private javax.swing.JButton jButtonInscriureParticipant;
    private javax.swing.JButton jButtonSortida;
    private javax.swing.JButton jButtonSortit;
    private javax.swing.JButton jButtonStats;
    private javax.swing.JLabel textEdiciojLabel;
    // End of variables declaration//GEN-END:variables
}
