/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package cem.view.dialogsMenu2.subMenuMarxes;

import cem.controller.Controller;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author joellopez
 */
public class PosarTemps extends javax.swing.JDialog {

    /**
     * Creates new form PosarTemps
     */
    //atributos
    private String edicio; 
    private Controller controller; 
    
    
    // false es que aquesta finestra s'utilitza per la iniciada de començar a correr
    //contructor
    private boolean func = false;
    public PosarTemps(java.awt.Frame parent, boolean modal,boolean func,String edicio) {
        super(parent, modal);
        initComponents();
        controller = Controller.getInstance();
        this.func = func;
        
        this.edicio = edicio; 
        if (func){
            textLabel.setText(textLabel.getText() + "sortit");
            
        }else{
            textLabel.setText(textLabel.getText() + "arribat");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        textLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        posarBoton = new javax.swing.JButton();
        dorsalTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jButton1.setText("SORTIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textLabel.setFont(new java.awt.Font("Fira Code", 1, 18)); // NOI18N
        textLabel.setForeground(new java.awt.Color(255, 255, 255));
        textLabel.setText("Introdueix el Dorsal de la persona que ha ");

        jLabel2.setText("(aquest temps ve donat per el sistema)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(textLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        posarBoton.setText("Posar Temps");
        posarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posarBotonActionPerformed(evt);
            }
        });

        dorsalTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dorsalTextField.setText("Dorsal");
        dorsalTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dorsalTextFieldFocusGained(evt);
            }
        });
        dorsalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dorsalTextFieldActionPerformed(evt);
            }
        });
        dorsalTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dorsalTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(posarBoton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dorsalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(dorsalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(posarBoton)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //boton salir
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    //valida que los datos coincidan con alguna inscripcion y añade la hora de salida/llegada
    private void posarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posarBotonActionPerformed
        try {
            if (dorsalTextField.getText().matches("[0-9]+")){
            if (controller.existDorsal(Integer.parseInt(dorsalTextField.getText()), Integer.parseInt(edicio))) {
                if (func) {
                    controller.putTimes(dorsalTextField.getText(), edicio);
                    JOptionPane.showMessageDialog(this, "S'ha posat el temps de tornada del participant", "Informació", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    if (controller.gettimesbyDorsal(dorsalTextField.getText(), edicio) != null) {
                        controller.putTimesa(dorsalTextField.getText(), edicio);
                        JOptionPane.showMessageDialog(this, "S'ha posat el temps de arribada del participant", "Informació", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Aquest concursant encara no ha sortit", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Aquest dorsal no existeix en aquesta marxa", "Error", JOptionPane.ERROR_MESSAGE);
            }}
            else{
                JOptionPane.showMessageDialog(this, "Aquest dorsal no es posible (nomes valors numerics)", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            System.out.println("Este error no se deberia dar " + e.getMessage());
        }
        dispose();
    }//GEN-LAST:event_posarBotonActionPerformed

    private void dorsalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dorsalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dorsalTextFieldActionPerformed

    private void dorsalTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dorsalTextFieldKeyReleased
        //Nothing
    }//GEN-LAST:event_dorsalTextFieldKeyReleased

    //mira el valor del dorsalTextField
    private void dorsalTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dorsalTextFieldFocusGained
        if (dorsalTextField.getText().equals("Dorsal")){
            dorsalTextField.setText("");
        }
    }//GEN-LAST:event_dorsalTextFieldFocusGained

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dorsalTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton posarBoton;
    private javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables
}
